# speficy your job type, such as tensorflow and pytorch
container_image: deepcluster/tensorflow:1.12-python3.6

# provide known dataset name or local datasets
dataset_name: cifar10
dataset_path:

# number of GPU used to train, default it 1
worker_required: 1

# command to run
# use the enviornment variable $DATASET to access dataset
# and write output to $OUTPUT
command: python main.py --dataset_path $DATASET --output_path $OUTPUT

# you can also define your config here
# config.yaml will be placed next to main.py
# so you can access your config from code from "./config.yaml"
train_steps: 100
num_gpus: 1
variable_strategy: GPU
use_distortion_for_training: True
log_device_placement: False
num_intra_threads: 0
num_layers: 44
train_batch_size: 128
eval_batch_size: 100
momentum: 0.9
weight_decay: 0.0002
learning_rate: 0.1
sync: False
num_inter_threads: 0
data_format:
batch_norm_decay: 0.997
batch_norm_epsilon: 0.00001